kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-user-access-view
  namespace: web
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["get, list"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get, list"]
